# curl -i -X POST   -H "Accept:application/json" -H "Content-Type:application/json" localhost:8083/connectors/ -d '{ "name": "kudu-connector", "config": { "connector.class": "personal.leo.kafka_connect_kudu.KuduSinkConector", "tasks.max": "1","topics.regex":"hdp04.test.t.*","masterAddresses":"test02","key.converter":"personal.leo.kafka_connect_kudu.converter.JSONObjectConverter","value.converter":"personal.leo.kafka_connect_kudu.converter.JSONObjectConverter"} }'
POST test01:10500/connectors/
Accept: application/json
Content-Type: application/json

{
  "name": "sink-kudu-s1-s_sum",
  "config": {
    "connector.class": personal.leo.kafka_connect_kudu.kudu.KuduSinkConector,
    "topics.regex": "s_sum",
    "masterAddresses": "test01:7051,test02:7051,test03:7051",
    "kuduTableName": "presto.s1.s_sum",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "value.converter": "org.apache.kafka.connect.storage.StringConverter",
    "kafkaBrokers": "test01:10001,test02:10001,test03:10001",
    "inputMsgType": "kafkaMsg"
  }
}


###
# curl -i -X DELETE -H "Accept:application/json" -H "Content-Type:application/json" localhost:8083/connectors/kudu-connector
DELETE test01:10500/connectors/sink-kudu-s1-s_sum
Accept: application/json
Content-Type: application/json

###
GET   test01:10500/connectors

###

