# curl -i -X POST   -H "Accept:application/json" -H "Content-Type:application/json" localhost:8083/connectors/ -d '{ "name": "kudu-connector", "config": { "connector.class": "personal.leo.kafka_connect_kudu.KuduSinkConector", "tasks.max": "1","topics.regex":"hdp04.test.t.*","masterAddresses":"test02","key.converter":"personal.leo.kafka_connect_kudu.JSONObjectConverter","value.converter":"personal.leo.kafka_connect_kudu.JSONObjectConverter"} }'
POST hdp09:10200/connectors/
Accept: application/json
Content-Type: application/json

{
  "name": "hdp04-connector",
  "config": {
    "connector.class": "io.debezium.connector.mysql.MySqlConnector",
    "database.hostname": "hdp04",
    "database.port": "3306",
    "database.user": "root",
    "database.password": "1",
    "database.server.id": "172016101001",
    "database.server.name": "hdp04",
    "database.include.list": "^test[0-9]*$,azkaban",
    "table.include.list": "^test[0-9]*\\.t7_[0-9]+$,^azkaban\\.exec[A-Za-z0-9_]*$",
    "decimal.handling.mode": "string",
    "database.history.kafka.bootstrap.servers": "hdp09:10001",
    "database.history.kafka.topic": "history.hdp04"
  }
}

###
# curl -i -X POST   -H "Accept:application/json" -H "Content-Type:application/json" localhost:8083/connectors/ -d '{ "name": "kudu-connector", "config": { "connector.class": "personal.leo.kafka_connect_kudu.KuduSinkConector", "tasks.max": "1","topics.regex":"hdp04.test.t.*","masterAddresses":"test02","key.converter":"personal.leo.kafka_connect_kudu.JSONObjectConverter","value.converter":"personal.leo.kafka_connect_kudu.JSONObjectConverter"} }'
POST hdp09:10200/connectors/
Accept: application/json
Content-Type: application/json

{
  "name": "src-dbz-mysql-hdp04-azkaban-execution_jobs",
  "config": {
    "connector.class": "io.debezium.connector.mysql.MySqlConnector",
    "database.hostname": "hdp04",
    "database.port": "3306",
    "database.user": "root",
    "database.password": "1",
    "database.server.id": "172016101001",
    "database.server.name": "hdp04",
    "database.include.list": "azkaban",
    "table.include.list": "azkaban\\.execution_jobs",
    "decimal.handling.mode": "string",
    "database.history.kafka.bootstrap.servers": "hdp09:10001",
    "database.history.kafka.topic": "history.src-dbz-mysql-hdp04-azkaban-execution_jobs"
  }
}

###

# curl -i -X DELETE -H "Accept:application/json" -H "Content-Type:application/json" localhost:8083/connectors/kudu-connector
DELETE hdp09:10200/connectors/hdp04-connector
Accept: application/json
Content-Type: application/json


###

# curl -i -X DELETE -H "Accept:application/json" -H "Content-Type:application/json" localhost:8083/connectors/kudu-connector
DELETE hdp09:10200/connectors/src-dbz-mysql-hdp04-azkaban-execution_jobs
Accept: application/json
Content-Type: application/json


###

GET   hdp09:10200/connectors

###

